[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
spin_wheel = "21HrGEnTMroXcp54bTCQKmgYS3uvbczsMRV6cBWGAnDV"

[programs.devnet]
spin_wheel = "EFnej75ZjJwieQzb2KdeDM2GiLDJQK8aiXWdjd3TbUAn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
# cluster = "devnet"
# wallet = "./admin-wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# test = "yarn run mocha -t 1000000an tests/"
create-admin = "node scripts/create-admin-wallet.js"
