[toolchain]
rust = "nightly"
anchor_version = "0.28.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
spin_wheel = "EFnej75ZjJwieQzb2KdeDM2GiLDJQK8aiXWdjd3TbUAn"

[programs.devnet]
spin_wheel = "EFnej75ZjJwieQzb2KdeDM2GiLDJQK8aiXWdjd3TbUAn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./admin-wallet-keypair.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
create-admin = "node scripts/create-admin-wallet.js"
