[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
spin_wheel = "AUSCcZQqFbidkXRMrPzNRy9irum2StmJX1Fdit3ejoXs"

[programs.devnet]
spin_wheel = "EFnej75ZjJwieQzb2KdeDM2GiLDJQK8aiXWdjd3TbUAn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
# cluster = "devnet"
# wallet = "./admin-wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/spin-wheel.ts tests/spin-wheel-game-setup.ts"
test-errors = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/spin-wheel-error-paths.ts"
create-admin = "node scripts/create-admin-wallet.js"
